environment:
  name: "HockeyEnv"
  mode: "NORMAL"              # or "TRAIN_SHOOTING", "TRAIN_DEFENSE"
  opponent_type: "basic_weak" # or "basic_strong", "none", "self_play"
  max_episode_steps: 300      # how many steps in an episode (if you want to override env default)

training:
  max_episodes: 1000
  max_timesteps: 250  # per episode
  seed: 42
  log_interval: 20
  save_interval: 200
  render: false
  train_iter: 32
  use_wandb: false
  wandb_project: "MyDreamerProject"
  wandb_entity: "mm08728"

models:
  dreamer:
    name: "DreamerV3"
    config:
      latent_dim: 32
      wm_hidden_size: 64
      actor_hidden_size: 64
      critic_hidden_size: 64
      world_model_lr: 1e-3
      actor_lr: 1e-4
      critic_lr: 1e-4
      discount: 0.99
      buffer_size: 100000
      batch_size: 64
      grad_updates_per_step: 1

evaluation:
  n_episodes: 10
  max_steps_per_episode: 200
  metrics:
    - "mean_return"
    - "episode_length"
